name: cocteles_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:

  flutter:
    sdk: flutter

  #Utility
  http: ^1.3.0
  provider: ^6.1.4
  logger:
  lottie:
  mime:
  url_launcher:
  connectivity_plus:
  flutter_native_splash:
  flutter_dotenv: ^5.2.1
  image_picker: ^1.0.0
  file_selector: ^0.9.0
  socket_io_client: ^3.1.2

  #Video
  path:
  path_provider:
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  #youtube_player_flutter: ^8.1.2
  #flutter_inappwebview: ^5.8.0
  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #State management
  get: ^4.7.2
  get_storage: ^2.1.1
  grpc: ^4.0.4
  protobuf: ^4.0.0
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
  # - assets/logos/
  #  - assets/icons/
  #  - assets/images/on_boarding_images/
  #  - assets/images/animations/
  #  - assets/images/user/
