// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUnir2_r-7VK1wZyViDgzZROjpyXHMA2M',
    appId: '1:976286983451:android:7955c501ee1de625fedfbe',
    messagingSenderId: '976286983451',
    projectId: 'cocteles-app',
    storageBucket: 'cocteles-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj-Mzozp6-xty2jZ_8dIiHKKe09V6k2ww',
    appId: '1:976286983451:ios:e75c7af16af8024cfedfbe',
    messagingSenderId: '976286983451',
    projectId: 'cocteles-app',
    storageBucket: 'cocteles-app.firebasestorage.app',
    iosBundleId: 'com.example.coctelesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj-Mzozp6-xty2jZ_8dIiHKKe09V6k2ww',
    appId: '1:976286983451:ios:e75c7af16af8024cfedfbe',
    messagingSenderId: '976286983451',
    projectId: 'cocteles-app',
    storageBucket: 'cocteles-app.firebasestorage.app',
    iosBundleId: 'com.example.coctelesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0h92acnyAUc1xAK2L526g6m1wBVF4Oy8',
    appId: '1:976286983451:web:3cccf4a8f1a8fbaafedfbe',
    messagingSenderId: '976286983451',
    projectId: 'cocteles-app',
    authDomain: 'cocteles-app.firebaseapp.com',
    storageBucket: 'cocteles-app.firebasestorage.app',
  );
}
